package com.htmltoapk.studio.generator

import com.htmltoapk.studio.data.model.CacheMode
import com.htmltoapk.studio.data.model.Orientation
import com.htmltoapk.studio.data.model.PermissionsConfig
import com.htmltoapk.studio.data.model.ProjectConfig
import com.htmltoapk.studio.data.model.UserAgentMode
import com.htmltoapk.studio.data.model.WebViewConfig

/**
 * In-code source templates for the generated Android WebView project.
 * Every template returns a fully-formed file string — no placeholders left
 * un-substituted.
 */
internal object Templates {

    // ----------------------------------------------------------------- ROOT

    fun settingsGradle(): String = """
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "GeneratedWebViewApp"
include(":app")
""".trimIndent()

    fun rootBuildGradle(): String = """
// Top-level build file
plugins {
    id("com.android.application") version "8.5.2" apply false
    id("org.jetbrains.kotlin.android") version "2.0.21" apply false
}
""".trimIndent()

    fun gradleProperties(): String = """
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
""".trimIndent()

    fun wrapperProps(): String = """
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-8.9-bin.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
""".trimIndent()

    fun gitignore(): String = """
*.iml
.gradle
/local.properties
/.idea
.DS_Store
/build
/captures
.externalNativeBuild
.cxx
""".trimIndent()

    fun readme(project: ProjectConfig): String = """
# ${project.appName}

Generated by HTML to APK Studio.

## Build
1. Open this folder in Android Studio.
2. Let Gradle sync.
3. Press **Run** or `./gradlew assembleRelease` to build an APK.

Package: `${project.packageName}`
Version: ${project.version}
Source type: ${project.sourceType.name}
""".trimIndent()

    // ----------------------------------------------------------------- APP MODULE

    fun appBuildGradle(project: ProjectConfig): String {
        val adv = project.advanced
        val signingBlock = if (project.signing.keystoreUri.isNotBlank()) """
    signingConfigs {
        create("release") {
            storeFile = file(System.getenv("KEYSTORE_FILE") ?: "")
            storePassword = System.getenv("KEYSTORE_PASSWORD") ?: ""
            keyAlias = System.getenv("KEY_ALIAS") ?: ""
            keyPassword = System.getenv("KEY_PASSWORD") ?: ""
        }
    }
""".trimIndent() else ""
        val releaseSigning = if (project.signing.keystoreUri.isNotBlank())
            "        signingConfig = signingConfigs.getByName(\"release\")" else ""
        return """
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "${project.packageName}"
    compileSdk = ${adv.targetSdk}

    defaultConfig {
        applicationId = "${project.packageName}"
        minSdk = ${adv.minSdk}
        targetSdk = ${adv.targetSdk}
        versionCode = 1
        versionName = "${project.version}"
    }
$signingBlock
    buildTypes {
        debug {
            isMinifyEnabled = false
        }
        release {
            isMinifyEnabled = ${adv.proguard}
            ${if (adv.proguard) "isShrinkResources = true" else ""}
            ${if (adv.proguard) "proguardFiles(getDefaultProguardFile(\"proguard-android-optimize.txt\"), \"proguard-rules.pro\")" else ""}
$releaseSigning
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.activity:activity-ktx:1.9.2")
    implementation("androidx.webkit:webkit:1.11.0")
}
""".trimIndent()
    }

    fun proguardRules(pkg: String): String = """
# Keep WebView client classes
-keep class $pkg.** { *; }

# Keep WebView JS bridge interfaces (annotated with @JavascriptInterface)
-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}
""".trimIndent()

    // ----------------------------------------------------------------- SOURCES

    fun appClass(project: ProjectConfig): String = """
package ${project.packageName}

import android.app.Application

class App : Application()
""".trimIndent()

    fun mainActivity(project: ProjectConfig, entryHtml: String): String {
        val w = project.web
        val immersiveBlock = if (w.immersive) """
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            window.insetsController?.apply {
                hide(android.view.WindowInsets.Type.statusBars() or android.view.WindowInsets.Type.navigationBars())
                systemBarsBehavior = android.view.WindowInsetsController.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
            }
        } else {
            @Suppress("DEPRECATION")
            window.decorView.systemUiVisibility = window.decorView.systemUiVisibility or
                (View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY or View.SYSTEM_UI_FLAG_FULLSCREEN or View.SYSTEM_UI_FLAG_HIDE_NAVIGATION)
        }
""".trimIndent() else ""

        val fullscreenBlock = if (w.fullscreen) """
        window.setFlags(
            WindowManager.LayoutParams.FLAG_FULLSCREEN,
            WindowManager.LayoutParams.FLAG_FULLSCREEN
        )
""".trimIndent() else ""

        val keepScreenOn = if (w.keepScreenOn) "        window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)" else ""

        val orientationCode = when (project.orientation) {
            Orientation.AUTO -> ""
            Orientation.PORTRAIT -> "        requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT"
            Orientation.LANDSCAPE -> "        requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE"
        }

        return """
package ${project.packageName}

import android.annotation.SuppressLint
import android.os.Build
import android.os.Bundle
import android.view.View
import android.view.WindowManager
import android.webkit.WebChromeClient
import android.webkit.WebResourceRequest
import android.webkit.WebSettings
import android.webkit.WebView
import android.webkit.WebViewClient
import android.content.pm.ActivityInfo
import androidx.activity.ComponentActivity
import androidx.activity.OnBackPressedCallback
import androidx.core.view.WindowCompat

class MainActivity : ComponentActivity() {

    private lateinit var webView: WebView

    @SuppressLint("SetJavaScriptEnabled")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
$orientationCode
${if (w.edgeToEdge) "        WindowCompat.setDecorFitsSystemWindows(window, false)" else ""}
$fullscreenBlock
$immersiveBlock
$keepScreenOn
        webView = WebView(this).apply {
            setContentView(this)
            configure()
            loadUrl("file:///android_asset/$entryHtml")
        }
        onBackPressedDispatcher.addCallback(this, object : OnBackPressedCallback(true) {
            override fun handleOnBackPressed() {
                if (this@MainActivity::webView.isInitialized && webView.canGoBack()) webView.goBack()
                else { isEnabled = false; onBackPressedDispatcher.onBackPressed() }
            }
        })
    }

    private fun WebView.configure() {
        settings.apply {
            ${webSettingsLines(w)}
        }
        webViewClient = object : WebViewClient() {
            override fun shouldOverrideUrlLoading(view: WebView, request: WebResourceRequest): Boolean {
                view.loadUrl(request.url.toString())
                return true
            }
        }
        webChromeClient = WebChromeClient()
    }
}
""".trimIndent()
    }

    private fun webSettingsLines(w: WebViewConfig): String {
        val b = StringBuilder()
        b.appendLine("javaScriptEnabled = ${w.javaScript}")
        b.appendLine("domStorageEnabled = ${w.domStorage}")
        b.appendLine("allowMixedContent = WebSettings.MIXED_CONTENT_${if (w.mixedContent) "ALWAYS_ALLOW" else "NEVER_ALLOW"}")
        b.appendLine("cacheMode = ${cacheModeConstant(w.cacheMode)}")
        when (w.userAgentMode) {
            UserAgentMode.DEFAULT -> {}
            UserAgentMode.DESKTOP -> b.appendLine("userAgentString = \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36\"")
            UserAgentMode.CUSTOM -> if (w.customUserAgent.isNotBlank()) b.appendLine("userAgentString = \"${w.customUserAgent.replace("\"", "\\\"")}\"")
        }
        b.appendLine("displayZoomControls = ${w.zoom}")
        b.appendLine("builtInZoomControls = ${w.zoom}")
        b.appendLine("mediaPlaybackRequiresUserGesture = ${!w.mediaPlayback}")
        b.appendLine("allowFileAccess = ${w.fileAccess}")
        b.appendLine("allowContentAccess = ${w.fileAccess}")
        b.appendLine("loadsImagesAutomatically = ${w.loadRemote}")
        b.appendLine("blockNetworkLoads = ${!w.loadRemote}")
        return b.toString().trimEnd()
    }

    private fun cacheModeConstant(mode: CacheMode): String = when (mode) {
        CacheMode.DEFAULT -> "WebSettings.LOAD_DEFAULT"
        CacheMode.NO_CACHE -> "WebSettings.LOAD_NO_CACHE"
        CacheMode.CACHE_ELSE_NETWORK -> "WebSettings.LOAD_CACHE_ELSE_NETWORK"
        CacheMode.NETWORK_ELSE_CACHE -> "WebSettings.LOAD_CACHE_NORMAL"
        CacheMode.CACHE_ONLY -> "WebSettings.LOAD_CACHE_ONLY"
    }

    fun webViewScreen(project: ProjectConfig): String = """
package ${project.packageName}

import android.webkit.WebView
import android.webkit.WebViewClient

/**
 * Optional WebView wrapper retained for future extensibility
 * (pull-to-refresh, deep-link handling, custom error pages).
 */
class WebViewHost(private val view: WebView) {
    init {
        view.webViewClient = WebViewClient()
    }

    fun load(url: String) = view.loadUrl(url)
}
""".trimIndent()

    // ----------------------------------------------------------------- RESOURCES

    fun stringsXml(project: ProjectConfig): String = """
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">${escapeXml(project.appName)}</string>
</resources>
""".trimIndent()

    fun colorsXml(project: ProjectConfig): String = """
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="status_bar">${project.advanced.statusBarColor}</color>
    <color name="nav_bar">${project.advanced.navBarColor}</color>
    <color name="ic_launcher_background">#0E1116</color>
</resources>
""".trimIndent()

    fun themesXml(project: ProjectConfig): String = """
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="Theme.App" parent="android:Theme.Material.NoActionBar">
        <item name="android:windowBackground">@android:color/black</item>
        <item name="android:statusBarColor">@color/status_bar</item>
        <item name="android:navigationBarColor">@color/nav_bar</item>
    </style>
</resources>
""".trimIndent()

    fun launcherForeground(): String = """
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <path android:fillColor="#8AB4F8"
        android:pathData="M54,18 L86,54 L54,90 L22,54 Z" />
    <path android:fillColor="#0E1116"
        android:pathData="M44,40 L64,40 L64,46 L50,46 L50,52 L62,52 L62,58 L50,58 L50,68 L44,68 Z" />
</vector>
""".trimIndent()

    fun launcherBackground(project: ProjectConfig): String = """
<?xml version="1.0" encoding="utf-8"?>
<color xmlns:android="http://schemas.android.com/apk/res/android"
    android:color="#0E1116" />
""".trimIndent()

    fun adaptiveIcon(): String = """
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
""".trimIndent()

    // ----------------------------------------------------------------- MANIFEST

    fun manifest(project: ProjectConfig): String {
        val p = project.permissions
        val permLines = buildList {
            if (p.internet) add("    <uses-permission android:name=\"android.permission.INTERNET\" />")
            if (p.networkState) add("    <uses-permission android:name=\"android.permission.ACCESS_NETWORK_STATE\" />")
            if (p.storage) add("    <uses-permission android:name=\"android.permission.READ_EXTERNAL_STORAGE\" android:maxSdkVersion=\"32\" />")
            if (p.camera) add("    <uses-permission android:name=\"android.permission.CAMERA\" />")
            if (p.microphone) add("    <uses-permission android:name=\"android.permission.RECORD_AUDIO\" />")
            if (p.location) add("    <uses-permission android:name=\"android.permission.ACCESS_FINE_LOCATION\" />")
            if (p.notifications && project.advanced.targetSdk >= 33) add("    <uses-permission android:name=\"android.permission.POST_NOTIFICATIONS\" />")
            if (p.vibrate) add("    <uses-permission android:name=\"android.permission.VIBRATE\" />")
        }.joinToString("\n")

        val orientationAttr = when (project.orientation) {
            Orientation.AUTO -> "unspecified"
            Orientation.PORTRAIT -> "portrait"
            Orientation.LANDSCAPE -> "landscape"
        }
        return """
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

$permLines

    <application
        android:name=".App"
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:theme="@style/Theme.App"
        android:usesCleartextTraffic="${project.web.mixedContent}"
        android:allowBackup="true">

        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:screenOrientation="$orientationAttr"
            android:configChanges="orientation|screenSize|keyboardHidden|uiMode">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
""".trimIndent()
    }

    private fun escapeXml(text: String): String =
        text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&apos;")
}
